# Generated by Django 4.0.2 on 2022-02-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ability',
            field=models.CharField(default='', max_length=50),
        ),
    ]
